url: http://hsvruby.github.com
auto: true
permalink: /:year/:month/:day/:title
pygments: true
markdown: maruku
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
exclude:
- README.md
- Rakefile
